Created converter between poloidal and toroidal
itpplasma/libneo pull request #27
Opened 2024-01-29 19:30 UTC by GeorgGrassler

Created converter between poloidal and toroidal
  magnetic flux (similar to FluxLabelConverter).
  A seperate class was written, as
  * FluxLabelConverter does not need the absolut values of the fluxes
  * it allows to cross-test the 2 converters agains each other

  Further Updates:
  * Fixed spelling/convention errors in FluxLabelConverter
  * Added test for new FluxConverter

2024-02-02 15:10 UTC, pazathoth requested changes

2024-02-02 15:10 UTC, pazathoth commented on tests/python/test_flux_converter.py
> +    from numpy.testing import assert_allclose
move import to top of function/module

2024-02-03 10:37 UTC, GeorgGrassler commented on python/libneo/flux_label_converter.py
In principle yes, they could be easily combined. The reason I initially decided to split it was, that I wanted to keep the label converters as slime as possible. For the FluxLabel conversion only the q-profile is needed, for the Flux conversion the absolute values of the flux (at axis and edge) is needed as well. One could write one single class that requires q-profile AND flux at the boundaries as input, where the main functionality is the flux conversion and the label conversion is a special case use of it.

2024-02-05 11:01 UTC, GeorgGrassler commented on python/libneo/flux_converter.py
> +        return psipol
Done

2024-02-05 11:01 UTC, GeorgGrassler commented on python/libneo/flux_converter.py
> +    print('toroidal flux psipol and phitor of a given flux surface.')
Done

2024-02-05 11:03 UTC, GeorgGrassler commented on tests/python/test_flux_converter.py
> +    from numpy.testing import assert_allclose
Done

2024-02-05 13:11 UTC, GeorgGrassler commented on tests/python/test_flux_converter.py
> +        print("Generating alternative_phitor_profile failed. Skipping test.")
Obsolute now as, FluxLabelConverter & FluxConverter were fused into one class

2024-02-12 14:20 UTC, pazathoth approved these changes

2024-02-12 14:20 UTC, krystophny commented
@GeorgGrassler check [#b1e0fa6](https://github.com/itpplasma/libneo/pull/27/commits/b1e0fa6fb9182cf29a616261dacfd838f9e4e1a0) for naming convention changes.

2024-02-12 14:21 UTC, merged